language: node_js
node_js:
- '0.10'
env: ENVIRONMENT=production
before_script:
- npm install
- npm install bower
- bower install
- npm install grunt-cli
- grunt
deploy:
  provider: s3
  bucket: thorvarium
  skip_cleanup: true
  local_dir: bin
  secret_access_key:
    secure: 5RgFkgZgbx/BYt62ZABa7zdZ0CpZwhZ3DbH+WWZHJeYuSCzJR5FBls32753LQQorjzCn/9lrti6fu1658X9bmr+JSrTDX1icSIvbeCE3XdyQffJgfrUEDahL+eyvu/petarBIhwZrMnTZPLB238aekiwQqYKW0CEHQTrMPfjSUc=
  access_key_id:
    secure: B/fu74fYgoCtGiRLyU1i7K9R6mCmhBd9d5gdd3/AX01fA72hQwGwpCPd/LsDhcO9d+CT/F03CrJiiikhd+GImVGPz8/RDeocxyzuDgwpWpGkPz3Q0WRFAWe7/9Bpo4cYGtSv6Y7nZ8uYqy4jdRp+9SYWDTNs+Ri/avYfkRARoPw=
