language: node_js
node_js:
- '0.10'
env: ENVIRONMENT=production
before_script:
- npm install
- npm install bower
- bower install
- npm install grunt-cli
- grunt
deploy:
  provider: s3
  access_key_id: AKIAIOXAGGTDWK53UFFA
  secret_access_key: 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
  bucket: thorvarium
  skip_cleanup: true
  local_dir: bin